echo ""
echo ""
echo ""
echo "alias tags='ctags -R *'"
echo "alias gcf='git cat-file'"
echo "alias gcfp='git cat-file -p'"

echo "PATH=\$PATH:~/bin/"
echo "export EDITOR=/usr/bin/vim"
echo "#export PS4='+\${BASH_SOURCE}:\${LINENO}:\${FUNCNAME[0]}: '"
