echo "set nu"
echo "set laststatus=2"
echo "set syntax=on"
echo "set hlsearch"
echo "set mouse=a"
echo "set autowrite"
echo "set autoread"
echo "set hidden"
echo "filetype on"
echo "set tags=./tags,tags;\$HOME"
echo ""
echo "set background=dark"
echo "set showcmd"
echo "set showmatch"
echo "set ignorecase"
echo "set smartcase"
echo "set incsearch"
echo "set hidden"
echo "set mouse=a"
echo ""
echo "set tabstop=4"
echo "set softtabstop=4"
echo "set shiftwidth=4"
echo "set autoindent"
echo "set cindent"
echo "set cinoptions={0,1s,t0,n-2,p2s,(03s,=.5s,>1s,=1s,:1s"
echo "set ruler"
echo "set backspace=2"
echo ""
echo "if has(\"autocmd\")"
echo "  au BufReadPost * if line(\"'\\\"\") > 1 && line(\"'\\\"\") <= line(\"$\") | exe \"normal! g'\\\"\" | endif"
echo "endif"
echo ""
echo "set cscopetag"
echo "map qq :qa!<CR>"
echo "map tt :TlistToggle<CR>"
echo "map <C-Left> <C-w>h"
echo "map <C-Right> <C-w>l"
echo "map ds :%s/\\s\\+$//g<CR>"
echo ""
echo "let Tlist_Ctags_Cmd = '/usr/bin/ctags'  \"告知系统生成tag的程序的位置"
echo "let Tlist_Show_One_File = 1                   \"不同时显示多个文件的tag，只显示当前文件的"
echo "let Tlist_Exit_OnlyWindow = 1                 \"如果taglist窗口是最后一个窗口，则退出vim"
echo "let Tlist_Use_Right_Window = 1                 \"在左侧窗口中显示taglist窗口"
echo ""
echo "\"set laststatus=2"
echo "\"set statusline+=%F"
echo "\"set statusline=%F%m%r%h%w%=\\ [ft=%Y]\\ %{\\\"[fenc=\\\".(&fenc==\\\"\\\"?&enc:&fenc).((exists(\\\"+bomb\\\")\\ &&\\ &bomb)?\\\"+\\\":\\\"\\\").\\\"]\\\"}\\ [ff=%{&ff}]\\ [asc=%03.3b]\\ [hex=%02.2B]\\ [pos=%04l,%04v][%p%%]\\ [len=%L]"
